### ISSUE TITLE
Unhandled UNASSIGNED state of connector

### ISSUE THREAD

**Issue by arnaboss** [gunjdesai/kafka-connect-monit#10]
@gunjdesai As per the kafka connect version on confluent 5.0, whenever a new connector is added/deleted the all the connectors rebalance, sending them to UNASSIGNED state for a short duration of time.

When sending alerts for connector, we should whitelist UNASSIGNED state and not send mailers during this state

**Comment by gunjdesai** [comment]
@arnaboss - Thanks for pointing out the issue and also for the PR for fixing it. 
This should be fixed in the `0.2` release
